"""
backtest_engine.py — AIGOFIN ML Package
=========================================
Integrates backtesting using the Backtrader framework.

Responsibilities:
- Load historical stock data
- Run strategies generated by strategy_engine
- Evaluate strategy performance
- Return performance summary (profit, max drawdown, win rate, sharpe ratio)

This module uses wrapper integration, keeping Backtrader source untouched.
"""

from typing import Any, Dict, Union
import pandas as pd

try:
    import backtrader as bt
    _BT_AVAILABLE = True
except ImportError:
    # Safely handle the absence of Backtrader; gracefully return errors.
    _BT_AVAILABLE = False


_BtStrategyBase = bt.Strategy if _BT_AVAILABLE else object

class StrategyWrapper(_BtStrategyBase):
    """
    Adapter class bridging the Backtrader engine with AIGOFIN's StrategyEngine.
    Iteratively calls the external strategy's generate_signal() on each bar.
    """
    params = (
        ('strategy_engine', None),
        ('verbose', False)
    )

    def __init__(self):
        if not _BT_AVAILABLE:
            raise ImportError("Backtrader is not installed.")
        self.strategy_engine = self.params.strategy_engine
        if not self.strategy_engine:
            raise ValueError("A strategy_engine object must be provided to run backtest.")

    def next(self):
        # Fetch current bar data
        features = {
            "open": self.data.open[0],
            "high": self.data.high[0],
            "low": self.data.low[0],
            "close": self.data.close[0],
            "volume": self.data.volume[0],
        }

        # Query AIGOFIN's StrategyEngine for trading decision
        # The external engine expects standard inputs and returns a dict with 'signal'.
        decisions = self.strategy_engine.generate_signal(features)
        signal = decisions.get("signal", 0)

        # Standard execution rules mapping
        if not self.position:
            if signal == 1:
                self.buy()
            elif signal == -1:
                self.sell()
        else:
            if self.position.size > 0 and signal == -1:
                self.close()  # flatten long
                self.sell()   # enter short
            elif self.position.size < 0 and signal == 1:
                self.close()  # flatten short
                self.buy()    # enter long
            elif signal == 0:
                pass          # hold constraint


def load_historical_data(data_source: Union[str, pd.DataFrame]) -> pd.DataFrame:
    """
    Resolves data source into a workable DataFrame for Backtrader feeds.
    """
    if isinstance(data_source, str):
        df = pd.read_csv(data_source, parse_dates=['Date'], index_col='Date')
    elif isinstance(data_source, pd.DataFrame):
        df = data_source.copy()
        date_cols = [c for c in df.columns if c.lower() in ('date', 'datetime', 'timestamp')]
        if not isinstance(df.index, pd.DatetimeIndex) and date_cols:
            df[date_cols[0]] = pd.to_datetime(df[date_cols[0]])
            df.set_index(date_cols[0], inplace=True)
    else:
        raise TypeError("data_source must be a file path string or pandas DataFrame.")

    # Canonicalize required columns
    required = ['open', 'high', 'low', 'close', 'volume']
    lower_cols = {c.lower(): c for c in df.columns}
    for req in required:
        if req not in lower_cols:
            df[req] = 0.0
        elif req != lower_cols[req]:
            df.rename(columns={lower_cols[req]: req}, inplace=True)
            
    return df


def run_backtest(
    data_source: Union[str, pd.DataFrame], 
    strategy_engine: Any, 
    initial_cash: float = 100_000.0, 
    commission: float = 0.001
) -> Dict[str, Any]:
    """
    Main function for the backtesting engine.
    Wraps the Backtrader routines strictly via the public API to evaluate an external strategy.
    
    Expected Metrics: profit, max drawdown, win rate, sharpe ratio
    """
    if not _BT_AVAILABLE:
        return {"error": "Backtrader not installed. Run 'pip install backtrader' to utilize backtesting."}

    cerebro = bt.Cerebro()

    # Load and map historical data
    df = load_historical_data(data_source)
    data = bt.feeds.PandasData(dataname=df)
    cerebro.adddata(data)

    # Attach AIGOFIN strategies
    cerebro.addstrategy(StrategyWrapper, strategy_engine=strategy_engine)

    # Configure Broker properties
    cerebro.broker.setcash(initial_cash)
    cerebro.broker.setcommission(commission=commission)

    # Attach Analyzers for requested KPIs
    cerebro.addanalyzer(bt.analyzers.TradeAnalyzer, _name="trades")
    cerebro.addanalyzer(bt.analyzers.DrawDown, _name="drawdown")
    cerebro.addanalyzer(bt.analyzers.SharpeRatio, _name="sharpe", riskfreerate=0.0, timeframe=bt.TimeFrame.Days)

    # Execution phase
    starting_value = cerebro.broker.getvalue()
    results = cerebro.run()
    
    if not results:
        return {"error": "Backtest failed or returned no results."}
        
    strategy_instance = results[0]
    final_value = cerebro.broker.getvalue()

    # Evaluation phase: Extracts metrics from the analyzers
    analyzers = strategy_instance.analyzers
    trade_info = analyzers.trades.get_analysis()
    drawdown_info = analyzers.drawdown.get_analysis()
    sharpe_info = analyzers.sharpe.get_analysis()

    # Format Metrics: Profit
    profit = final_value - starting_value

    # Format Metrics: Max Drawdown
    max_drawdown = drawdown_info.max.drawdown if 'max' in drawdown_info else 0.0

    # Format Metrics: Win Rate
    total_trades = trade_info.total.closed if 'total' in trade_info and 'closed' in trade_info.total else 0
    won_trades = trade_info.won.total if 'won' in trade_info and 'total' in trade_info.won else 0
    win_rate = (won_trades / total_trades * 100.0) if total_trades > 0 else 0.0

    # Format Metrics: Sharpe Ratio
    sharpe_ratio = sharpe_info.get('sharperatio', 0.0)
    if sharpe_ratio is None:
        sharpe_ratio = 0.0

    # Output requested performance summary
    return {
        "starting_value": round(starting_value, 2),
        "final_value": round(final_value, 2),
        "profit": round(profit, 2),
        "profit_pct": round((profit / starting_value) * 100, 2),
        "max_drawdown": round(max_drawdown, 2),
        "win_rate": round(win_rate, 2),
        "sharpe_ratio": round(sharpe_ratio, 3),
        "total_trades": total_trades
    }

class BacktestEngine:
    """
    Backward-compatibility class for legacy sub-modules (like ai_strategy_discovery.py).
    Standardizes on the new run_backtest function.
    """
    def run_backtest(self, config: dict) -> dict:
        # Extract parameters from the legacy config dictionary
        symbol = config.get("symbol", "AAPL")
        # In the context of discovery, we might not have a strategy_engine yet,
        # so we'll pass None or a mock if needed.
        return run_backtest(symbol, strategy_engine=None)

if __name__ == "__main__":
    import sys
    import os
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    # Quick test
    import pandas as pd
    import numpy as np
    from .strategy_engine import StrategyEngine
    import numpy as np
    
    # Generate generic data matrix to verify API interaction
    dates = pd.date_range('2023-01-01', periods=100)
    df_dummy = pd.DataFrame({
        'open': np.random.uniform(90, 110, 100),
        'high': np.random.uniform(105, 115, 100),
        'low': np.random.uniform(85, 95, 100),
        'close': np.random.uniform(90, 110, 100),
        'volume': np.random.uniform(1_000, 5_000, 100)
    }, index=dates)

    engine = StrategyEngine()
    summary = run_backtest(df_dummy, engine)
    print("Execution Finished. Performance Summary: \n", summary)
